"""
alerts.py

Contains rule-based security detection functions for the network traffic
monitoring project.
"""

from collections import defaultdict
import ipaddress

from src.database.queries import (
    get_known_device,
    get_recent_average_packet_rate,
    insert_known_device,
    insert_security_alert,
    update_device_last_seen,
)

# Alert thresholds
from src.config import (
    EXCESSIVE_PACKET_THRESHOLD,
    PORT_SCAN_THRESHOLD,
    TRAFFIC_SPIKE_MULTIPLIER,
)


def is_local_address(ip_address):
    """
    Returns True if an IP address is private or link-local.

    Invalid, unspecified, multicast, and public addresses are excluded.
    """

    try:
        address = ipaddress.ip_address(ip_address)

        return (
            not address.is_unspecified
            and not address.is_multicast
            and (
                address.is_private
                or address.is_link_local
            )
        )

    except ValueError:
        return False

def detect_new_devices(connection, packets):
    """
    Detects source IP addresses that have not previously been observed.
    """

    # Track IPs already processed during this analysis window.
    checked_ips = set()

    # Examine each packet's source IP.
    for packet in packets:
        timestamp, src_ip, _, _, _, _, _ = packet

        # Skip missing, duplicate, public, multicast, or unspecified addresses.
        if (
                not src_ip
                or src_ip in checked_ips
                or not is_local_address(src_ip)
        ):
            continue

        checked_ips.add(src_ip)

        # Check whether this local device has already been observed.
        device = get_known_device(connection, src_ip)

        if device is None:
            insert_known_device(connection, src_ip, timestamp)

            # New device detected.
            insert_security_alert(
                connection=connection,
                alert_timestamp=timestamp,
                alert_type="New Device",
                severity="Info",
                source_ip=src_ip,
                destination_ip=None,
                destination_port=None,
                description=f"New source IP observed: {src_ip}"
            )

            print(f"New device alert generated for {src_ip}")

        else:
            # Existing device found, update last seen timestamp.
            update_device_last_seen(connection, src_ip, timestamp)

def detect_traffic_spike(
    connection,
    window_start,
    window_end,
    packet_count
):
    """
    Detects packet rates that exceed the recent traffic baseline.
    """

    # Calculate the current packet rate.
    duration_seconds = (window_end - window_start).total_seconds()

    if duration_seconds <= 0:
        return

    current_rate = packet_count / duration_seconds

    # Retrieve the recent average packet rate.
    average_rate = get_recent_average_packet_rate(
        connection,
        before_time=window_start
    )

    if average_rate is None or average_rate == 0:
        return

    # Generate an alert if traffic exceeds the configured threshold.
    if current_rate > average_rate * TRAFFIC_SPIKE_MULTIPLIER:
        multiplier = current_rate / average_rate

        insert_security_alert(
            connection=connection,
            alert_timestamp=window_end,
            alert_type="Traffic Spike",
            severity="Medium",
            source_ip=None,
            destination_ip=None,
            destination_port=None,
            description=(
                f"Packet rate reached {current_rate:.2f} packets/sec, "
                f"which is {multiplier:.2f} times the recent average."
            )
        )

        print("Traffic spike alert generated.")

def detect_excessive_packet_rate(connection, packets, window_end):
    """
    Detects source IPs generating unusually high packet counts.
    """

    # Count packets generated by each source IP.
    source_counts = defaultdict(int)

    for packet in packets:
        _, src_ip, _, _, _, _, _ = packet

        if src_ip:
            source_counts[src_ip] += 1

    # Check each source IP against the configured threshold.
    for src_ip, packet_count in source_counts.items():

        if packet_count > EXCESSIVE_PACKET_THRESHOLD:

            insert_security_alert(
                connection=connection,
                alert_timestamp=window_end,
                alert_type="Excessive Connection Rate",
                severity="Medium",
                source_ip=src_ip,
                destination_ip=None,
                destination_port=None,
                description=(
                    f"Source IP {src_ip} generated "
                    f"{packet_count} packets during the analysis window."
                )
            )

            print(f"Excessive packet-rate alert generated for {src_ip}")


def detect_port_scans(connection, packets, window_end):
    """
    Detects source IPs contacting many unique destination ports.
    """

    # Track every destination port contacted by each source IP.
    source_ports = defaultdict(set)

    for packet in packets:

        (
            _,
            src_ip,
            dst_ip,
            protocol,
            src_port,
            dst_port,
            packet_size
        ) = packet

        if src_ip and dst_port is not None:
            source_ports[src_ip].add(dst_port)

    # Check the number of unique ports contacted by each source IP.
    for src_ip, destination_ports in source_ports.items():

        unique_port_count = len(destination_ports)

        if unique_port_count > PORT_SCAN_THRESHOLD:

            insert_security_alert(
                connection=connection,
                alert_timestamp=window_end,
                alert_type="Possible Port Scan",
                severity="High",
                source_ip=src_ip,
                destination_ip=None,
                destination_port=None,
                description=(
                    f"Source IP {src_ip} contacted "
                    f"{unique_port_count} unique destination ports."
                )
            )

            print(f"Port scan alert generated for {src_ip}")